# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT backend.wsgi

default_expiration: "1m"

beta_settings:
  cloud_sql_instances: shosetsu:us-central1:shosetsu-instance

runtime_config:
  python_version: 3
# [END runtime]

handlers:
  - url: /static
    static_dir: static
