# Generated by Django 2.1.4 on 2018-12-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='project',
            new_name='project_id',
        ),
    ]
