# Generated by Django 2.1.4 on 2018-12-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0003_auto_20181224_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='project_id',
            new_name='project',
        ),
    ]
