# Generated by Django 2.1.4 on 2019-01-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0008_auto_20190106_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='element_type_id',
            new_name='element_type',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='elementfield',
            old_name='element_type_id',
            new_name='element_type',
        ),
        migrations.RenameField(
            model_name='elementtype',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='element_id',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='element_field_id',
            new_name='element_field',
        ),
    ]
