# Generated by Django 2.1.4 on 2019-01-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0009_auto_20190106_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default='Test Element', max_length=100),
            preserve_default=False,
        ),
    ]
