# Generated by Django 2.1.5 on 2019-01-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0011_auto_20190108_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elementvalue',
            unique_together={('element_instance', 'element_field')},
        ),
    ]
