# Generated by Django 2.1.5 on 2019-01-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0013_auto_20190123_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='element',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='element',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='elementfield',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='elementfield',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='elementinstance',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='elementinstance',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='elementvalue',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='elementvalue',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_date',
        ),
    ]
