# Generated by Django 2.1.4 on 2019-01-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0006_auto_20190106_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementfield',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
