# Generated by Django 2.1.4 on 2019-01-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0007_auto_20190106_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='element_type',
            new_name='element_type_id',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='elementfield',
            old_name='element_type',
            new_name='element_type_id',
        ),
        migrations.RenameField(
            model_name='elementtype',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='element_field',
            new_name='element_field_id',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='element',
            new_name='element_id',
        ),
        migrations.AlterField(
            model_name='elementfield',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
