# Generated by Django 2.1 on 2019-01-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shosetsu', '0010_element_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='elementtype',
            name='project',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='elementfield',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='elementvalue',
            name='element',
        ),
        migrations.AddField(
            model_name='elementfield',
            name='element',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='element_fields', to='shosetsu.Element'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shosetsu.Project'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='shosetsu.Book'),
        ),
        migrations.AlterField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='shosetsu.Project'),
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='element_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_values', to='shosetsu.ElementField'),
        ),
        migrations.DeleteModel(
            name='ElementType',
        ),
        migrations.AddField(
            model_name='elementinstance',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_instances', to='shosetsu.Element'),
        ),
        migrations.AddField(
            model_name='elementinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_instances', to='shosetsu.Project'),
        ),
        migrations.AddField(
            model_name='elementvalue',
            name='element_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='element_values', to='shosetsu.ElementInstance'),
            preserve_default=False,
        ),
    ]
